config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :users
  root "home#index"
  resources :keywords, only: [:index, :create, :show]
  
  namespace :v1 do
  	resources :keywords, only: [:index, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :user_keywords, dependent: :destroy
end

app/models/user_keyword.rb
class UserKeyword < ActiveRecord::Base
  belongs_to :user

  validates :user, :keyword,
    :top_adwords_count, :bottom_adwords_count, :total_adwords_count,
    :non_adwords_count, :total_link_count,
    :raw_html, presence: true

  default_scope { order('keyword asc') }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate_user!

	def index
		@keywords = current_user.user_keywords
		access_token = Doorkeeper::AccessToken.find_or_create_for(nil,current_user.id,nil,5040,true)
	end

end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  
  before_action :authenticate_user!

  def index
    redirect_to :controller => "home",:action => "index"
  end

  def create
    if params[:file].present?
      if params[:file].content_type == 'text/csv'
        parser = CsvParser.new(params[:file].tempfile)
        content = parser.read
        validated_content = parser.verify_keywords(content)
        render json: { code: 500, message: validated_content[:message], result: "unable to validate content of csv" } and return unless validated_content[:status]
        GoogleSearchJob.perform_later(validated_content[:keywords], current_user.id)
        redirect_to :controller => "home",:action => "index"
      else
        render json: { code: 500, message: "message", result: "error" } and return
      end
    else
      render json: { code: 500, message: "message", result: "keywords error" } and return
    end
  end

  def show
    @keyword = current_user.user_keywords.find_by_id(params[:id])
  end
end

app/controllers/v1/api_application_controller.rb
class V1::ApiApplicationController < ApplicationController
	before_action :doorkeeper_authorize!

  def current_user
    @current_user ||= User.find_by_id(
      doorkeeper_token.resource_owner_id
      ) unless doorkeeper_token.nil?
  end

  def doorkeeper_unauthorized_render_options(error: nil)
    { json: { error: "Not authorized" } }
  end
end

app/controllers/v1/keywords_controller.rb
class V1::KeywordsController < V1::ApiApplicationController
  
  protect_from_forgery with: :null_session, only: [:create]

  def index
    keywords = current_user.user_keywords
    render :json => keywords, :except => [:raw_html,:updated_at]
  end

  def create
    if params[:file].present?
      if params[:file].content_type == 'text/csv'
        parser = CsvParser.new(params[:file].tempfile)
        content = parser.read
        validated_content = parser.verify_keywords(content)
        render json: { code: 500, message: validated_content[:message], result: "unable to validate content of csv" } and return unless validated_content[:status]
        GoogleSearchJob.perform_later(validated_content[:keywords], current_user.id)
        render json: { code: 200, message: "Success", result: "Result generated successfully" } and return
      else
        render json: { code: 500, message: "Incorrect File type", result: "File type error" } and return
      end
    else
      render json: { code: 500, message: "Empty File", result: "File error" } and return
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="row csv-upload">
  <div class="upload-form">
    <%= form_tag '/keywords', multipart: true do %>
      <label for="file">File to Upload</label> <%= file_field_tag "file" %>
      <%= submit_tag "Upload", :class => "form-control btn btn-primary" %>
    <% end %>
  </div>
  
</div>

<% @keywords.each do |keyword| %>
  <div class="panel panel-default keyword-result">
    <div class="panel-heading">
      <%= keyword.keyword %> - <%= link_to 'View Html Page', keyword_path(keyword), :class => 'awe-btn awe-btn-1 awe-btn-medium' %>
    </div>
    <div class="panel-body">

      <div class="row">
        <div class="col-sm-4">
          <span>Total adwords count: <%= keyword.total_adwords_count %></span>
        </div>
        
        <div class="col-sm-4">
          <span>Top adwords count: <%= keyword.top_adwords_count %></span>
          <% if keyword.top_adwords_count > 0 %>
            <button type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#top-adword-<%= keyword.id%>" >
              view
            </button>
            <div id="top-adword-<%= keyword.id%>" class="modal fade" role="dialog">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Total Adwords on Top</h4>
                  </div>
                  <div class="modal-body">
                    <% JSON.parse(keyword.top_adword_urls).each_with_index do |link,i| %>
                      <p> <%= i + 1 %> - <%= link %></p>
                    <% end %>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>

              </div>
            </div>
          <% end %>
        </div>

        <div class="col-sm-4">
          <span>Bottom adwords count: <%= keyword.bottom_adwords_count %></span>
          <% if keyword.bottom_adwords_count > 0 %>
            <button type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#bottom-adword-<%= keyword.id%>" >
              view
            </button>
            <div id="bottom-adword-<%= keyword.id%>" class="modal fade" role="dialog">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Total Adwords on Right</h4>
                  </div>
                  <div class="modal-body">
                    <% JSON.parse(keyword.bottom_adword_urls).each_with_index do |link,i| %>
                      <p> <%= i + 1 %> - <%= link %></p>
                    <% end %>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>

              </div>
            </div>
          <% end %>
        </div>

      </div>

      <div class="row">
        <div class="col-sm-4">
          <span>Non Adwords count: <%= keyword.non_adwords_count %></span>
          <% if keyword.non_adwords_count > 0 %>
            <button type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#non-adword-<%= keyword.id%>" >
              view
            </button>
            <div id="non-adword-<%= keyword.id%>" class="modal fade" role="dialog">
              <div class="modal-dialog">
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Non Adwords URL</h4>
                  </div>
                  <div class="modal-body">
                    <% JSON.parse(keyword.non_adword_urls).each_with_index do |link,i| %>
                      <p> <%= i + 1 %> - <%= link_to link %></p>
                    <% end %>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>
                </div>

              </div>
            </div>
          <% end %>
        </div>

        <div class="col-sm-4">
          <span>Total links count: <%= keyword.total_link_count %></span>
        </div>

        <div class="col-sm-4">
          <span>Search Result: <%= keyword.total_search_result %></span>
        </div>
      </div>
      
    </div>
  </div>
<% end %>

app/views/keywords/show.html.erb
<%= @keyword.raw_html.html_safe %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nimbl3</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-default">
		  <div class="container-fluid">
		    <% if user_signed_in? %>
          <div class="navbar-header">
            Welcome <%= current_user.email.split("@")[0] %>
          </div>
        <% end %>
        <div class="navbar-header navbar-right">
		        <% if user_signed_in? %>
		        	<%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
		        <% else %>
		        	<%= link_to('Login', new_user_session_path)  %>
	        	<% end %>
		    </div>
		  </div>
		</nav>
    <div class="container">
  		<%= yield %>
    </div>
  </body>
</html>